id: PD14C77D4
initial_creation_type: ocr
source_metadata:
  volumes:
    d8b6a8ea228e450797ffdec3275eba2b:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: གཤིན་རྗེ་གཤེད་རིན་ཆེན་འབྱུང་ལྡན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
